name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-apk:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential git unzip python3-pip
        sudo apt install -y openjdk-8-jdk
        sudo apt install -y autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo6 cmake libffi-dev libssl-dev
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install kivy[base]==2.1.0
        pip install reportlab>=3.6.0
        pip install Pillow>=9.0.0
        pip install pandas>=1.3.0
        pip install openpyxl>=3.0.0
        pip install buildozer==1.4.0
        pip install cython==0.29.33
        
    - name: Build APK with Buildozer
      run: |
        export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
        cd card-game-generator-android/android_app/  # Navigate to the directory containing buildozer.spec
        buildozer android debug
        
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: card-game-generator-android/android_app/bin/*.apk 
        
    - name: List generated files
      run: |
        echo "Generated APK files:"
        ls -la bin/
        
    - name: Upload APK as release asset (if tagged)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: bin/*.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
